### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by gzhhhh-cute** [ursaj123/SuperUNET#1]
Hello！How much GPU memory is required to train this network? My GPU has about 24GB of memory, but it shows out of memory.

**Comment by ursaj123** [comment]
I trained it on my laptop's nvidia 2GB GPU, maybe you can try torch.empty_cache().
If the problem still persists, then can please give me the exact error?

**Comment by gzhhhh-cute** [comment]
I changed the skips in the downsample class from being a class attribute to a local variable. The original way of writing seemed to cause skips to accumulate and occupy memory over time. After the modification, this should no longer be an issue.Thanks！
class downsample(nn.Module):
    def __init__(self, channels = [1, 8, 16, 32, 64, 128]):
        super(downsample, self).__init__()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.channels = channels
        self.blocks = nn.ModuleList([])
        for i in range(5):
            self.blocks.append(resblock(self.channels[i], self.channels[i+1]))
        pass

    def forward(self, x):
        # x shape is (B, 3, H, W)
        skips = []
        for i in range(5):
            x = self.blocks[i](x) # (B, channels[i+1], H, W)
            skips.append(x) # (B, channels[i+1], H, W)
            if i < 4:
                x = self.pool(x) # (B, channels[i+1], H/2, W/2)
        return skips
